import de from 'react-intl/locale-data/de';
import { addLocaleData } from 'react-intl';

addLocaleData([...de]);

Telescope.strings.de = {
  "forms.submit": "Senden",
  "forms.cancel": "Abbrechen",

  "posts.new_post": "Neuer Beitrag",
  "posts.edit": "Bearbeiten",
  "posts.edit_success": "Beitrag “{title}” bearbeitet.",
  "posts.delete": "Löschen",
  "posts.delete_confirm": "Beitrag löschen: “{title}”?",
  "posts.delete_success": "Beitrag “{title}” gelöscht.",
  "posts.title": "Titel",
  "posts.url": "URL",
  "posts.body": "Text",
  "posts.categories": "Kategorien",
  "posts.thumbnailUrl": "Thumbnail URL",
  "posts.status": "Status",
  "posts.sticky": "Sticky",
  "posts.load_more": "Mehr laden",
  "posts.search": "Suche",
  "posts.view": "Anzeige",
  "posts.top": "Top",
  "posts.new": "Neu",
  "posts.best": "Beste",
  "posts.pending": "Anstehend",
  "posts.rejected": "Abgelehnt",
  "posts.scheduled": "Geplant",
  "posts.daily": "Täglich",
  "posts.clear_thumbnail": "Thumbnail entfernen",
  "posts.enter_thumbnail_url": "URL Eingeben",
  "posts.created_message": "Beitrag erstellt.",
  "posts.rate_limit_error": "Bitte {details} Sekunden warten vor dem nächsten Beitrag.",
  "posts.postedAt": "Erstellt",
  "posts.dateNotDefined": "Datum nicht festgelegt",

  "comments.comments": "Kommentare",
  "comments.count": "{count, plural, =0 {Keine Kommentare} one {# Kommentar} other {# Kommentare}}",
  "comments.new": "Neuer Kommentar",
  "comments.no_comments": "Keine Kommentare anzuzeigen.",
  "comments.reply": "Antwort",
  "comments.edit": "Bearbeiten",
  "comments.delete": "Löschen",
  "comments.delete_confirm": "Kommentar “{body}” löschen?",
  "comments.delete_success": "Kommentar “{body}” gelöscht.",
  "comments.please_log_in": "Bitte einloggen zum Kommentieren.",
  "comments.parentCommentId": "ID übergeordneter Kommentar",
  "comments.topLevelCommentId": "ID oberster Kommentar",
  "comments.body": "Text",
  "comments.rate_limit_error": "Bitte {details} Sekunden warten vor dem nächsten Kommentar.",

  "users.profile": "Profil",
  "users.complete_profile": "Profil vervollständigen",
  "users.edit_account": "Konto Bearbeiten",
  "users.edit_success": "Benutzer “{name}” bearbeitet",
  "users.log_in": "Anmelden",
  "users.log_out": "Abmelden",
  "users.telescope.bio": "Über mich",
  "users.telescope.displayName": "Anzeigename",
  "users.telescope.email": "E-Mail",
  "users.telescope.twitterUsername": "Twitter Username",
  "users.telescope.website": "Webseite",
  "users.telescope.groups": "Gruppen",
  "users.notifications": "Benachrichtigungen",
  "users.telescope.notifications_users": "Benachrichtigungen über neue User",
  "users.telescope.notifications_posts": "Benachrichtigungen über neue Beiträge",
  "users.telescope.newsletter_subscribeToNewsletter": "Newsletter bestellen",
  "users.admin": "Admin",
  "users.isAdmin": "Admin",
  "users.posts": "Beiträge",
  "users.please_log_in": "Bitte anmelden",
  "users.cannot_post": "Entschuldigung, Sie haben keine Berechtigung Beiträge zu erstellen.",

  "categories": "Kategorien",
  "categories.all": "Alle Kategorien",
  "categories.edit": "Kategorie Bearbeiten",
  "categories.new": "Neue Kategorie",
  "categories.delete": "Kategorie löschen",
  "categories.name": "Name",
  "categories.description": "Beschreibung",
  "categories.order": "Sortierung",
  "categories.slug": "Slug",
  "categories.image": "Bild",
  "categories.parentId": "ID übergeordnete Kategorie",

  "settings": "Einstellungen",
  "settings.json_message": "Hinweis: Bereits in der Datei <code>settings.json</code> vorhandene Einstellungen werden deaktiviert.",
  "settings.edit": "Einstellungen bearbeiten",
  "settings.edited": "Einstellungen bearbeitet (bitte neu laden).",
  "settings.title": "Titel",
  "settings.siteUrl": "Site URL",
  "settings.tagline": "Tagline",
  "settings.description": "Beschreibung",
  "settings.siteImage": "Site Image",
  "settings.defaultEmail": "Standard E-Mail",
  "settings.mailUrl": "Mail URL",
  "settings.scoreUpdate": "Punkte Update",
  "settings.postInterval": "Beitragsintervall",
  "settings.RSSLinksPointTo": "RSS Links Point To",
  "settings.commentInterval": "Kommentarintervall",
  "settings.maxPostsPerDay": "Maximale Anzahl Beiträge pro Tag",
  "settings.startInvitesCount": "Anzahl Einladungen zu Beginn",
  "settings.postsPerPage": "Beiträge pro Seite",
  "settings.logoUrl": "Logo URL",
  "settings.logoHeight": "Logo Höhe",
  "settings.logoWidth": "Logo Breite",
  "settings.faviconUrl": "Favicon URL",
  "settings.twitterAccount": "Twitter Konto",
  "settings.facebookPage": "Facebook Seite",
  "settings.googleAnalyticsId": "Google Analytics ID",
  "settings.locale": "Locale",
  "settings.requireViewInvite": "Einladung zum Ansehen erforderlich",
  "settings.requirePostInvite": "Einladung zum Posten erforderlich",
  "settings.requirePostsApproval": "Beiträge müssen freigeschaltet werden",
  "settings.scoreUpdateInterval": "Zeit bis zur Neuberechnung der Punkte",

  "app.loading": "Wird geladen…",
  "app.404": "Entschuldigung, wir konnten die Seite nicht finden.",
  "app.powered_by": "Gebaut mit Telescope",
  "app.or": "Oder",

  "newsletter": "Newsletter",
  "newsletter.subscribe": "Abonnieren",
  "newsletter.unsubscribe": "Abbestellen",
  "newsletter.subscribe_prompt": "Newsletter Abonnieren",
  "newsletter.email": "Ihre E-Mail",
  "newsletter.success_message": "Danke für das Abonnieren.",

  "admin": "Admin",
  "notifications": "Benachrichtigungen",
}
